FEEDS = [
    {
        "id": "nyt",
        "name": "New York Times",
        "short": "NYT",
        "urls": [
            "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
            "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
            "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
        ],
        "category": "News",
        "color": "#000000",
        "tab": "today",
    },
    {
        "id": "guardian",
        "name": "The Guardian",
        "short": "Guardian",
        "urls": [
            "https://www.theguardian.com/world/rss",
            "https://www.theguardian.com/us-news/rss",
        ],
        "category": "News",
        "color": "#005689",
        "tab": "today",
    },
    {
        "id": "reuters",
        "name": "Reuters",
        "short": "Reuters",
        "urls": [
            "https://news.google.com/rss/search?q=reuters&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "News",
        "color": "#FF8000",
        "tab": "today",
        "is_google_news": True,
    },
    {
        "id": "ap",
        "name": "AP News",
        "short": "AP",
        "urls": [
            "https://news.google.com/rss/search?q=site:apnews.com&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "News",
        "color": "#CC0000",
        "tab": "today",
        "is_google_news": True,
    },
    {
        "id": "latimes",
        "name": "LA Times",
        "short": "LA Times",
        "urls": [
            "https://www.latimes.com/rss2.0.xml",
        ],
        "category": "News",
        "color": "#003F7E",
        "tab": "today",
    },
    {
        "id": "wsj",
        "name": "Wall Street Journal",
        "short": "WSJ",
        "urls": [
            "https://news.google.com/rss/search?q=site:wsj.com&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "News",
        "color": "#0274B6",
        "tab": "today",
        "is_google_news": True,
    },
    {
        "id": "deadline",
        "name": "Deadline",
        "short": "Deadline",
        "urls": [
            "https://deadline.com/feed/",
        ],
        "category": "Entertainment",
        "color": "#E31937",
        "tab": "entertainment",
    },
    {
        "id": "variety",
        "name": "Variety",
        "short": "Variety",
        "urls": [
            "https://variety.com/feed/",
        ],
        "category": "Entertainment",
        "color": "#8B1A1A",
        "tab": "entertainment",
    },
    {
        "id": "gq",
        "name": "GQ",
        "short": "GQ",
        "urls": [
            "https://www.gq.com/feed/rss",
        ],
        "category": "Lifestyle",
        "color": "#1A1A1A",
        "tab": "today",
    },
    {
        "id": "waterpolo",
        "name": "Water Polo",
        "short": "Water Polo",
        "urls": [
            'https://news.google.com/rss/search?q=%22water+polo%22&hl=en-US&gl=US&ceid=US:en',
        ],
        "category": "Sports",
        "color": "#0066CC",
        "tab": "sports",
        "is_google_news": True,
    },
    {
        "id": "rolex",
        "name": "Rolex",
        "short": "Rolex",
        "urls": [
            "https://news.google.com/rss/search?q=Rolex+watch+new&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "Lifestyle",
        "color": "#006039",
        "tab": "today",
        "is_google_news": True,
    },
]
