FEEDS = [
    {
        "id": "nyt",
        "name": "New York Times",
        "short": "NYT",
        "urls": [
            "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
            "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
            "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
        ],
        "category": "News",
        "color": "#000000",
        "tab": "today",
        "paywall": True,
    },
    {
        "id": "guardian",
        "name": "The Guardian",
        "short": "Guardian",
        "urls": [
            "https://www.theguardian.com/world/rss",
            "https://www.theguardian.com/us-news/rss",
        ],
        "category": "News",
        "color": "#005689",
        "tab": "today",
    },
    {
        "id": "reuters",
        "name": "Reuters",
        "short": "Reuters",
        "urls": [
            "https://news.google.com/rss/search?q=reuters&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "News",
        "color": "#FF8000",
        "tab": "today",
        "is_google_news": True,
    },
    {
        "id": "ap",
        "name": "AP News",
        "short": "AP",
        "urls": [
            "https://news.google.com/rss/search?q=site:apnews.com&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "News",
        "color": "#CC0000",
        "tab": "today",
        "is_google_news": True,
    },
    {
        "id": "latimes",
        "name": "LA Times",
        "short": "LA Times",
        "urls": [
            "https://www.latimes.com/rss2.0.xml",
        ],
        "category": "News",
        "color": "#003F7E",
        "tab": "today",
    },
    {
        "id": "wsj",
        "name": "Wall Street Journal",
        "short": "WSJ",
        "urls": [
            "https://news.google.com/rss/search?q=site:wsj.com&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "News",
        "color": "#0274B6",
        "tab": "today",
        "is_google_news": True,
        "paywall": True,
    },
    {
        "id": "deadline",
        "name": "Deadline",
        "short": "Deadline",
        "urls": [
            "https://deadline.com/feed/",
        ],
        "category": "Entertainment",
        "color": "#E31937",
        "tab": "entertainment",
    },
    {
        "id": "variety",
        "name": "Variety",
        "short": "Variety",
        "urls": [
            "https://variety.com/feed/",
        ],
        "category": "Entertainment",
        "color": "#8B1A1A",
        "tab": "entertainment",
    },
    {
        "id": "gq",
        "name": "GQ",
        "short": "GQ",
        "urls": [
            "https://www.gq.com/feed/rss",
        ],
        "category": "Lifestyle",
        "color": "#1A1A1A",
        "tab": "magazines",
        "is_magazine": True,
    },
    {
        "id": "waterpolo",
        "name": "Water Polo",
        "short": "Water Polo",
        "urls": [
            'https://news.google.com/rss/search?q=%22water+polo%22&hl=en-US&gl=US&ceid=US:en',
        ],
        "category": "Sports",
        "color": "#0066CC",
        "tab": "sports",
        "is_google_news": True,
    },
    {
        "id": "rolex",
        "name": "Rolex",
        "short": "Rolex",
        "urls": [
            "https://news.google.com/rss/search?q=Rolex+watch+new&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "Lifestyle",
        "color": "#006039",
        "tab": "today",
        "is_google_news": True,
    },
    # ── New additions ──────────────────────────────────────────────────────
    {
        "id": "bbc",
        "name": "BBC News",
        "short": "BBC",
        "urls": [
            "http://feeds.bbci.co.uk/news/rss.xml",
            "http://feeds.bbci.co.uk/news/world/rss.xml",
        ],
        "category": "News",
        "color": "#B80000",
        "tab": "today",
    },
    {
        "id": "atlantic",
        "name": "The Atlantic",
        "short": "Atlantic",
        "urls": [
            "https://www.theatlantic.com/feed/all/",
        ],
        "category": "News",
        "color": "#C0392B",
        "tab": "magazines",
        "is_magazine": True,
        "paywall": True,
    },
    {
        "id": "wired",
        "name": "Wired",
        "short": "Wired",
        "urls": [
            "https://www.wired.com/feed/rss",
        ],
        "category": "Tech",
        "color": "#000000",
        "tab": "magazines",
        "is_magazine": True,
    },
    {
        "id": "time",
        "name": "Time",
        "short": "Time",
        "urls": [
            "https://time.com/feed/",
        ],
        "category": "News",
        "color": "#CC0000",
        "tab": "magazines",
        "is_magazine": True,
    },
    {
        "id": "vogue",
        "name": "Vogue",
        "short": "Vogue",
        "urls": [
            "https://www.vogue.com/feed/rss",
        ],
        "category": "Lifestyle",
        "color": "#000000",
        "tab": "magazines",
        "is_magazine": True,
    },
    {
        "id": "hollywoodreporter",
        "name": "Hollywood Reporter",
        "short": "THR",
        "urls": [
            "https://www.hollywoodreporter.com/feed/",
        ],
        "category": "Entertainment",
        "color": "#1C3F6E",
        "tab": "entertainment",
    },
    {
        "id": "rollingstone",
        "name": "Rolling Stone",
        "short": "RS",
        "urls": [
            "https://www.rollingstone.com/feed/",
        ],
        "category": "Entertainment",
        "color": "#D4232A",
        "tab": "magazines",
        "is_magazine": True,
    },
    {
        "id": "espn",
        "name": "ESPN",
        "short": "ESPN",
        "urls": [
            "https://www.espn.com/espn/rss/news",
        ],
        "category": "Sports",
        "color": "#CC0000",
        "tab": "sports",
    },
    {
        "id": "bloomberg",
        "name": "Bloomberg",
        "short": "Bloomberg",
        "urls": [
            "https://news.google.com/rss/search?q=site:bloomberg.com&hl=en-US&gl=US&ceid=US:en",
        ],
        "category": "Business",
        "color": "#1B1B1B",
        "tab": "today",
        "is_google_news": True,
        "paywall": True,
    },
    # ── Free alternatives ──────────────────────────────────────────────────
    {
        "id": "npr",
        "name": "NPR",
        "short": "NPR",
        "urls": ["https://feeds.npr.org/1001/rss.xml"],
        "category": "News",
        "color": "#00A0E3",
        "tab": "today",
    },
    {
        "id": "pbs",
        "name": "PBS NewsHour",
        "short": "PBS",
        "urls": ["https://www.pbs.org/newshour/feeds/rss/headlines"],
        "category": "News",
        "color": "#00A0D1",
        "tab": "today",
    },
    {
        "id": "axios",
        "name": "Axios",
        "short": "Axios",
        "urls": ["https://api.axios.com/feed/"],
        "category": "News",
        "color": "#FF4B00",
        "tab": "today",
    },
    {
        "id": "thehill",
        "name": "The Hill",
        "short": "The Hill",
        "urls": ["https://thehill.com/feed/"],
        "category": "News",
        "color": "#1A1A2E",
        "tab": "today",
    },
    {
        "id": "politico",
        "name": "Politico",
        "short": "Politico",
        "urls": ["https://www.politico.com/rss/politicopicks.xml"],
        "category": "News",
        "color": "#E21D2C",
        "tab": "today",
    },
    {
        "id": "vox",
        "name": "Vox",
        "short": "Vox",
        "urls": ["https://www.vox.com/rss/index.xml"],
        "category": "News",
        "color": "#FF3300",
        "tab": "today",
    },
    {
        "id": "propublica",
        "name": "ProPublica",
        "short": "ProPublica",
        "urls": ["https://feeds.propublica.org/propublica/main"],
        "category": "News",
        "color": "#231F20",
        "tab": "today",
    },
    {
        "id": "cnbc",
        "name": "CNBC",
        "short": "CNBC",
        "urls": ["https://www.cnbc.com/id/100003114/device/rss/rss.html"],
        "category": "Business",
        "color": "#0072CE",
        "tab": "today",
    },
    {
        "id": "quartz",
        "name": "Quartz",
        "short": "Quartz",
        "urls": ["https://qz.com/feed"],
        "category": "Business",
        "color": "#3CBFAE",
        "tab": "today",
    },
    {
        "id": "marketwatch",
        "name": "MarketWatch",
        "short": "MarketWatch",
        "urls": ["https://www.marketwatch.com/rss/topstories"],
        "category": "Business",
        "color": "#28A745",
        "tab": "today",
    },
    {
        "id": "dw",
        "name": "Deutsche Welle",
        "short": "DW",
        "urls": ["https://rss.dw.com/rdf/rss-en-all"],
        "category": "News",
        "color": "#00A8E6",
        "tab": "today",
    },
    {
        "id": "france24",
        "name": "France 24",
        "short": "France 24",
        "urls": ["https://www.france24.com/en/rss"],
        "category": "News",
        "color": "#F0001E",
        "tab": "today",
    },
]
